id: IBED6DD0D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-03-30T12:32:49+00:00'
last_modified: '2022-06-16T05:07:06.792336+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN21836
  title: ལོ་པན་གྱི་རྣམ་ཐར་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    D649:
      image_group_id: I3CN21897
      title: ''
      total_pages: ''
      order: 1
      base_file: D649.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
